[package]
name = "pcap-parse"
version = "0.1.0"
description = "PCAP test tool for rusticata parsers"
license = "LGPL-2.1+"
keywords = ["Rusticata","pcap","protocol","parser","nom"]
homepage = "https://github.com/rusticata/pcap-parse"
repository = "https://github.com/rusticata/pcap-parse.git"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[dependencies]
argparse = "*"
pcap = "0.5.7"
pnet = "0.13.0"
nom = "^2.0"
log = "*"
env_logger = "*"
lazy_static = "0.1.*"
rusticata = { git = "https://github.com/rusticata/rusticata.git" }
