[package]
name = "pcap-parse"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[dependencies]
pcap = "0.5.7"
pnet = "0.13.0"
nom = "1.2.4"
tls-parser = { git = "https://github.com/rusticata/tls-parser.git" }
